ARGON2_TIME_COST = 3
ARGON2_MEMORY_COST = 65536
ARGON2_PARALLELISM = 2
ARGON2_SALT_LENGTH = 32
ARGON2_KEY_LENGTH = 32

HKDF_INFO_ENCRYPTION = b"file_encryption_key"
HKDF_INFO_METADATA = b"metadata_encryption_key"
HKDF_INFO_SIGNING = b"signing_key"
HKDF_INFO_VAULT = b"vault_root_key"

AES_KEY_LENGTH = 32
AES_NONCE_LENGTH = 12
AES_TAG_LENGTH = 16

SEED_PHRASE_LENGTH = 12
RATE_LIMIT_MAX_ATTEMPTS = 5
RATE_LIMIT_LOCKOUT_TIME = 300
UUID_LENGTH = 32
