# Generated by Django 5.1.5 on 2026-04-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedvaultitem',
            name='cid',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='advancedvaultitem',
            name='tx_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
